### ISSUE TITLE
Please add a license file and a readme

### ISSUE THREAD

**Issue by unixorn** [gcarrarom/oh-my-guish#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file or a readme.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by gcarrarom** [comment]
Hi @unixorn, I've just added the Readme and the License.
Bear in mind this is just something I did to keep my aliases and functions in check. But feel free to share!
